<?php
/**
 * Theme Header Section for our theme.
 *
 * @package gosarin.com
 * @subpackage MyWpTheme
 * @since MyWpTheme 0.0
 */
?><!DOCTYPE html>

<!--[if IE 7]>
<html class="ie ie7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if !(IE 7) & !(IE 8)]><!-->
<html <?php language_attributes(); ?>>
    <!--<![endif]-->
    <head>
        <!-- Generic meta and utility tags -->
        <meta charset="<?php bloginfo('charset'); ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="profile" href="http://gmpg.org/xfn/11" />
        <link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
        <!-- Stylesheets -->
        <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/libweb/components-font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/dist/css/mywptheme.css" />
        <style>



            #menu-my-social-menu li a::before {
                display: inline-block;
                padding: 0 22px 0 0;
                font-family: FontAwesome;
                font-size: 20px;
                vertical-align: baseline;
                content: "\f005";
                color: #ccc;
            }

            #menu-my-social-menu li a[href*="facebook.com"]::before {
                content: '\f09a';
                color: #3b5998;
            }
            #menu-my-social-menu li a[href*="twitter.com"]::before {
                content: '\f099';
                color: #00aced;
            }
            #menu-my-social-menu li a[href*="plus.google.com"]::before {
                content: '\f0d5';
                color: #dd4b39;
            }
            #menu-my-social-menu li a[href*="youtube.com"]::before {
                content: '\f167';
                color: #bb0000;
            }
            #menu-my-social-menu li a[href*="pinterest.com"]::before {
                content: '\f0d2';
                color: #cb2027;
            }
            #menu-my-social-menu li a[href*="instagram.com"]::before {
                content: '\f16d';
                color: #517fa4;
            }

            #menu-my-social-menu li a span {
                display: none;
            }



        </style>
        <!-- Wordpress autogenerated - HEAD hook -->
        <?php
        wp_head();
        ?>
    </head>

    <body <?php body_class(); ?> style="background-color: #f2f2f2;">
    <div id="page"> <!-- Needed by WordPress 1.5 site architecture -->
        <?php
        get_template_part('template-parts/header/masthead');
        ?>        
        <?php
        get_template_part('template-parts/header/navbar');
        ?>
        <hr class="invisible">
        

