<?php
/**
 * Theme Header Section for our theme.
 *
 * @package gosarin.com
 * @subpackage MyWpTheme
 * @since MyWpTheme 0.0
 */
?><!DOCTYPE html>

<!--[if IE 7]>
<html class="ie ie7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if !(IE 7) & !(IE 8)]><!-->
<html <?php language_attributes(); ?>>
    <!--<![endif]-->
    <head>
        <!-- Generic meta and utility tags -->
        <meta charset="<?php bloginfo('charset'); ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="profile" href="http://gmpg.org/xfn/11" />
        <link rel="pingback" href="<?php bloginfo('pingback_url'); ?>" />
        <!-- Stylesheets -->
        <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/libweb/components-font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/dist/css/mywptheme.css" />
        <!-- Wordpress autogenerated - HEAD hook -->
        <?php
        wp_head();
        ?>
    </head>

    <body <?php body_class(); ?> style="background-color: #f2f2f2;"> <!-- TODO: proper plugin for body color -->
    <div id="page"> <!-- Needed by WordPress 1.5 site architecture -->
        <?php
        get_template_part('template-parts/header/masthead');
        ?>        
        <?php
        get_template_part('template-parts/header/navbar');
        ?>
        <hr class="invisible">
        

